### PR TITLE
use array to sort params instead of object

### PR DESCRIPTION
**Pull request by osminushkin**
Sorting of params changed to use array instead of object according to explanation in issue https://github.com/paymentwall/paymentwall-node/issues/11, point 2

### CODE REVIEW

**Comment by osminushkin** [comment]
Hi @paymentwall!
Could you take a look please?

**Comment by liufanhhh** [comment]
Hi Osminushkin,

We will look this with our colleague.

Thank you so much for your help :)

**Comment by liufanhhh** [comment]
Hi Osminushkin,

Could you please help to advise in what case the Sort Function will broken?

As we tested, it worked well.

Thanks,
Fan

**Comment by osminushkin** [comment]
Hi!

According to the standard there is no guarantee of iteration order for objects.
```javascript
var ns = {};
ns['b'] = 'b';
ns['a'] = 'a';
ns['2'] = '2';
ns['1'] = '1';
for (k in ns) {
  console.log(k);
}
```
The script above will print
`1 2 b a`

Of course, this is an abstract example just to show the case :)

**Comment by liufanhhh** [comment]
Hi,

But in the sort object code we use this:

``` javascript
    for (key in o) {
        if (o.hasOwnProperty(key)) {
            a.push(key);
        }
    }

    a.sort();
```

In this case, we will sort the keys no matter if they are in order.

Are you referring this part?

**Comment by osminushkin** [comment]
in `sortObject` you defined `sorted` to store sorted key-value and array `a` to store the keys from object and sort them.

You pushed the keys to the array and sorted it:
````javascript
for (key in o) {
    if (o.hasOwnProperty(key)) {
        a.push(key);
    }
}

a.sort();
```

but next you converted this array back to an object
````javascript
for (key = 0; key < a.length; key++) {
  sorted[a[key]] = o[a[key]];
}

return sorted;
```

in `pingback.js` when calculating signature:
````javascript
params = this.sortObject(params);
...
for (key in params) {
    ...
}
```

The thing is that you are sorting the array, but then iterating over the object and there is no guarantee of order of iterations, which you are trying to get by sorting

**Comment by liufanhhh** [comment]
Understand , thank you so much for helping!

We will fix this issue in next version :)

**Comment by liufanhhh** [comment]
Please refer to [issue 11](https://github.com/paymentwall/paymentwall-node/issues/11).

**Pull request closed without merging**
